services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"  # Puerto de PostgreSQL

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Puerto de la aplicación web
    env_file:
      - .env
    depends_on:
      - db  # Dependencia del servicio de base de datos

volumes:
  postgres_data:  # Volumen para persistencia de datos de PostgreSQL
